package com.hm.config.excel.temlate;

import com.hm.libcore.annotation.FileConfig;
import lombok.Data;

@Data
@FileConfig("tank_base")
public class TankBaseTemplate {
	private Integer id;
	private String name;
	private String desc;
	private Integer paper_id;
	private Integer type;
	private Integer country;
	private Integer rare;
	private Integer reform_type;
	private Integer star;
	private Integer atk;
	private Integer def;
	private Integer hp;
	private Float atk_add;
	private Float def_add;
	private Float hp_add;
	private Integer hit;
	private Integer dodge;
	private Integer crit;
	private Integer crit_def;
	private Float crit_dam;
	private Float crit_res;
	private String skill_id;
	private Integer atk_cd;
	private Integer ballistic;
	private Integer atk_type;
	private Integer atk_times;
	private Integer point_number;
	private Integer fist_atk;
	private Integer atk_ready_time;
	private String icon_b;
	private String icon_l;
	private String icon_head;
	private String icon_body;
	private String back_effect;
	private String dead_effect;
	private String csbPro;
	private String comefrom;
	private Integer shape_type;
	private Float fight_zoom;
	private Integer gacha_display;
	private Integer printing;
	private Integer attack_action;
	private Integer display_playerlist;
	private Integer driver_id;
	private Float big_zoom;
	private String friend;
	private Integer energy;
	private String tank_position;
	private String draw_position;
	private String tank_deviation;
	private Float proportion;
	private String sound_move;
	private String sound_idle;
	private String specail_point;
	private Integer trump_rate;
	private Integer active_unlock;
	private String tec_tree;
	private String tec_skill;
	private String tec_skill_replace;
	private String evolve_attr_rate;
	private String evolve_tec_rate;
	private String evolve_cost;
	private String evolve_addition;
	private Integer fetters;
	private String tank_speciality;
	private String magic_reform_skill;
    private String magic_reform_super_skill;
	private Integer magic_reform_bigskill;
	private Integer magic_reform_oldbigskill;
	private Integer magic_reform_superoldbigskill;
	private Integer super_reform_bigskill;
	private Integer xianding_type;
	private Integer sss_warpath;
	private String terrain_skill;
	private int fly_time;
}
