package com.hm.enums;
import lombok.Getter;


@Getter
public enum CommonValueType {
    TankDrawPrice(1, "坦克工厂绘制图纸价格"),
    TankShufflePrice(2, "坦克工厂刷新图纸价格"),
    TankLockPerPrice(3, "坦克工厂每锁定一个图纸，刷新增加价格"),
    TankPaperProbability(4, "坦克工厂每次绘制出现图纸的概率"),
    TankDrawDropId(5, "坦克工厂其他道具掉落"),
    FlopAllPrice(6,"全部翻牌的消耗的金币数"),
    FlopPrice(7,"翻不同牌的消耗的金币数"),
    TankSecondMp(11,"坦克每秒恢复能量"),
    TankLoseHpMp(12,"坦克每掉1%的血量恢复的能量"),
    KillUnitAddMp(13,"杀死敌方坦克恢复能量"),
    GuidCreate(14,"创建部落的时候的消耗"),
    GuildChangName(15,"部落改名价格（金砖）"),
    FlyDistanceRate(16,CommValueV2Type.Array_Double,"飞行距离比例"),
    ContrWarKill(17,"城战杀敌获得功勋"),
    ContrWarDeath(18,"飞行距离比例"),
	HonorWarKill(19,"城战杀敌获得功勋"),
    HonorWarOccupy(20,"城战占城获得荣誉"),
    HonorWarAssists(21,"城战助攻获得荣誉"),
    HonorWarDeath(22,"城战被杀获得荣誉"),
    TreasuryRate(24,"每收复一座城，征收的石油和钞票的量增加值"),
    AreanFreeTimes(26,"竞技场免费挑战次数"),
    GuildNameLength(30,"部落名字的数量"),
	leaveTime(31,"离开多长时间，才能再加入，创建部落"),
	FlagName(32,"部落旗帜上面字的数量"),
	reqSize(33,"最多申请加入部落数量"),
	vipMin(34, "创建部落最小vip等级"),
	legatusSize(35, "副部落长数量"),//副部落长的数量
	playerSize(36, "部落人数限制"),//部落人数的限制
	clearPlayerDays(37, "离线多少天自动退团"),
	Pvp1v1Honor(38, "城战单挑（偷袭）获得荣誉，无论输赢"),
	GuildClearInvite(39, "清除部落的邀请时间（分钟）"),
	GuildMoveMainCity(41, "部落迁都花费金砖"),
	MoraleMax(42, "士气上限"),
	MoraleMin(43, "士气下限"),
	MoraleReduceFight(44, "每场上限降低"),
	MoraleReduceSecond(45, "每场士气降低速度（X/秒）"),
	MoraleAtkDefRate(46, "士气上限每降低1点，攻防降低比例"),
	MoraleNotReduceSecond(47, "每场战斗前X秒，不降低士气"),
	ArenaSports(48,"竞技币"),
    FirstTankResearchSeniorId(49, "第一次抽奖必得坦克id"),
    GuildScoreWin(51, "国战胜利部落获得分数"),
    GuildScorePlayerReward(52, "领取国战奖励部落获得单位分数"),
    GuildCityScore(53, "国战胜利时部落按照当前领地数量获得单位分数（柏林除外）"),
    NoGuildWarNpcNum(55, "中立国战目标npc个数"),
    TowerFreeSweepNum(58, "使命之路每天免费扫荡boss关卡的次数"),
    GroupHorseMpTop(59, "座驾能量上限"),
    GroupHorseMpAddFrame(60, "座驾每帧恢复"),
    GroupHorseMpInit(61, "座驾初始能量"),
    PvpOilRate(63, "偷袭消耗石油比例"),
	TankFactoryIntro(65, "首次进科研中心的坦克展示"),
	TankFactoryIntroPrize(66, "首次进科研中心的研究的奖励"),
	CityScoreLow(69, "低级城每分钟国战积分"),
	CityScoreHigh(70, "中级城每分钟国战积分"),
	CityScoreRandom(71, "随机城每分钟国战积分"),
	GuildCash(72, "部落中，钞票捐献次数"),
	GuildGold(73, "部落中，金币捐献次数"),
	GuildResetTec(74, "重置部落的科技，消耗资源"),
	GuildResetTime(75, "重置部落的科技，冷却的时间（分钟）"),
	FristRechargeGiftId(76,CommValueV2Type.LIST_INT,"首冲礼包"),
	TradeProduce(77, "航运基础小时产出"),
	TradeSpeed(78, "航运基础速度 海里/小时"),
	TradeLoad(79, "航运基础载重"),
	TradeLimit(80, "航运交易预警值"),
	TradeBoatPrice(81, "航运船只价格（5条船，花金砖）"),
	ChangeNamePrice(82,"玩家改名价格花金砖(100金砖)"),
	AdvanceMinBei(83,"突击默认所需部队数量和敌军数量默认比"),
	TroopMoveSpeed(84,"两个城之间移动默认时间 秒"),
	SupplySpeed(86,"运镖每个城之间行驶时间(分钟)"),
	SupplyMaxNum(87,CommValueV2Type.LevelChoiceMode,"运镖可运个数和所需等级"),
	SupplyRobMaxNum(88,"运镖可抢夺成功次数"),
	SupplyRefresh(89,"运镖任务刷新价格（金砖）"),
	SupplyEnemyRefresh(90,"运镖掠夺刷新价格（钞票）"),
	GuildFirstAddReward(91,"首次创建或加入部落的奖励"),
	SSTankSingle(92, "SS坦克活动单抽价格"),
	SSTankTen(93, "SS坦克活动十连抽价格"),
	SSTankLuckyValue(94, "SS坦克活动幸运满值"),
	RechargeFeedBackMax(96,"充值回馈每日可领取最大次数"),
	RechargeFeedBackGold(97,"充值回馈每满多少金砖可领奖"),
	RechargeRebateLv(98,CommValueV2Type.MAP_INT_Double,"充值返利配置，根据等级返回相应的倍数"),
	RechargeRebateTimes(99,"充值返利人民币倍数"),
	LevelShopContinueDay(100,"等级商店开启后持续天数"),
	ShootingCount(101,"坦克打靶子弹数"),
	NormalRebelHour(102,CommValueV2Type.LIST_INT,"叛军武装刷新时间"),
	ParisId(103,"巴黎id"),
	RechargeSevenDay(104,"7天充值活动，持续天数"),
	BerlinCenterNpcNum(105,"首都战攻城精锐生成个数每个方向X支"),
	BerlinMainNpcNum(106,"首都战防守精锐生成个数，每个卫星城X支"),
	BerlinBombGold(107,"首都战炸弹价格（金砖）"),
	BerlinBombMaxTimes(108,"首都战炸弹次数"),
	BerlinBombHp(109,"首都战炸弹伤害"),
	BerlinCityMaxHp(110,"首都战复活点血量"),
	BerlinNpcLifeLine(111,"首都战生成防守精锐 条件，每掉多少血"),
	BerlinCloneGold(112,"首都战镜像价格（金砖）"),
	BerlinCloneReturn(113,"首都战每个镜像返还钞票石油数"),
	BerlinWorship(114,CommValueV2Type.LevelChoiceMode,"首都战膜拜掉落包"),
	ServerLvRate(115,"服务器等级比例"),
	OpenBerlinCityId(117,"解锁柏林战的城池id"),
	GuildWar3Threshold(118,"国战目标三阀值"),
	PlayerExpAdd(119,CommValueV2Type.LevelChoiceMode,"等级差经验加成值"),
	GuildImpeach(120, "部落长被弹劾的时间（多久未登陆，小时）"),
	GuildImpeachCoast(121, "弹劾部落长的消耗"),
	GuildImpeachLast(122, "弹劾部落长的时间（开始，结束时间段，小时）"),
	AnswerWrongReward(123,"答题失败单次奖励"),
	PlayerExpAddMinLv(125,"等级差经验加成值要求最低等级"),
	OverallWarMaxNum(129,"全面战争最大次数"),
	CityScoreLuck(130,CommValueV2Type.LevelChoiceMode,"国战2旗帜城分数"),
	TrumpWorship(131,"王牌演习膜拜掉落id"),
	TrumpReset(132,"王牌军演重置价格"),
	OverallWarOpenLv(133,"全面战争第一个玩家达到多少级开"),
	CustomTankMaxNum(134,"自定义坦克配置最大数量"),
	KfBetGold(139,"跨服战下注金砖和下注失败返还金砖"),
	TrumpPrizeRate(140,"王牌军演消耗石油兑换钞票比例"),
	GuildComandMinute(142,"部落指挥持续时间,分钟"),
	BeInvitedDayReward(143,"受邀每日奖励"),
	MergerServerWelfare(144, "合服奖励"),
	MergerServerHonor(145, "合服排行活动最低奖励领取条件（荣誉榜，荣誉值达到xx才能领取最低奖励）"),
	MergerServerTankCombat(146, "合服排行活动最低奖励领取条件（战车榜，最强战车战力达到xx才能领取最低奖励）"),
	MergerServerCombat(147, "合服排行活动最低奖励领取条件（战力榜，最大战力达到xx才能领取最低奖励）"),
	MergerServerRecharge(148, "合服排行活动最低奖励领取条件（充值榜，充值达到xx人民币）"),
	TankResearchDefaultRate(149,"SS坦克初始概率"),
	TankResearchGet(150,"第多少次高研必得S坦克"),
	BattleCallSoliderCost(151,"沙场点兵刷牌基础消耗金砖数"),
	BeInviteReward(152,"受邀一次性奖励"),
	CampImpeachGold(153,"弹劾需要元宝数"),
	CampLuckGold(154,"推荐阵营奖励元宝数"),
	CampApplyMaxTicket(155,"投票阶段每人最多可以投几票"),
	CampMainCityLinkNpcNum(156,"主城出兵的数量（主城周围的每个城池补兵队列数量上限）"),
	CampMainCityLinkNpcCD(157,"主城守卫军触发cd（分钟）"),
	KfSportsWorshipDrop(158,"跨服战膜拜奖励drop"),
	CampImpeachHour(159,"弹劾时间（小时）"),
	CampImpeachMinTicket(160,"弹劾最低人数"),
	MainCityMaxNpc(161,"主城守备军上限"),
	BeInviteLvLimit(162,"受邀人绑定时等级不能高于30级"),
	BindPhoneGiftId(164,"绑定手机号码giftid"),
	VipProveLv(165,"Vip认证最小等级"),
	RebelSplitMinute(166,"叛军武装分裂间隔时间（分钟）"),
	RebelNormalMaxNum(167,"叛军武装单支数量上限"),
	RebelDefNum(168,"叛军武装分裂留守数量"),
	RebelSplitMinNum(169,"叛军武装少于X支后不分裂"),
	RebelNormalCreateNum(170,CommValueV2Type.LevelChoiceMode,"叛军支数条件(占领多少比例城会出现叛军支数)"),
	GhostCampKill(171,"阵营目标数量、奖励"),
	GhostCityMaxNum(172,"幽靈小怪总数量"),
	GhostCityBossNum(173,"幽靈BOSS总数量"),
	ExpeditionFlopRate1(174,"手动翻牌第一次翻小红书 第二次得小红书的概率"),
	ExpeditionFlopRate2(175,"远征扫荡纯随机翻牌的概率"),
	TankResearchMaxLuckyValue(176,"抽奖幸运值最大值"),
	GuildBarrackWarReward(177,"国战中部落调兵的奖励"),
	CitySpicalHour(178,CommValueV2Type.LIST_INT,"城市特殊产出时间点"),
	ExpeditionBuffCost(179,"远征buff购买金砖数"),
	ExpeditionBuffLimit(180,"远征buff购买次数上限"),
	TankDrawItems(182,"绘制图纸1次所需绘制草图数量"),
	WarHelper_Oil_Limit(183,"自动挂机石油上限100w"),
	CampImpeachAddGold(184,"阵营弹劾，每多弹劾1次，增加金砖数"),
	CampAddRate(185,CommValueV2Type.LevelChoiceMode,"阵营援助BUFF，城池产出增加，荣誉获得速度"),
	BerlinWinReward(186,"首都战获胜部落奖励"),
	AddBuffRate(187,"【跨服资源战】同层部落占矿数每增加1，该层产出增加10%"),
	KfMineIp(188,"【跨服资源战】连接地址"),
	KfGarrisonGold(189,"【跨服资源战】派遣增援部队消耗20金砖"),
	KfDayFight(190,"【跨服资源战】玩家每天可战斗次数上限"),
	LoginFundPrice(191, "购买登陆基金的金砖价格"),
	ResSuddenStrikeBuyLimit(193,"【物资突袭】每日购买次数上限"),
	ResSuddenStrikeBuyCost(194,"【物资突袭】每日购买单次价格"),
	ConsumeGold(195,"金矿开采消费多少个金砖得一个矿镐"),
	ConsumeGoldMax(196,"金矿开采最多可得多少个矿镐"),
	RedPacketTotal(197,"红包中钻石总数"),
	RedPacketCount(198,"红包分配人数"),
	RedPacketMax(199,"分红包比例上限（用的时候需要除100）"),
	RedPacketMin(200,"分红包比例下限（用的时候需要除100）"),
	BerlinDevoteKillPlayer(201,"【首都战】杀死玩家获得贡献值"),
	BerlinDevoteTroopDeath(202,"【首都战】部队死亡获得贡献值"),
	BerlinDevote1Hp(203,"【首都战】撞城掉1点耐久获得贡献值"),
	BerlinDevoteCloneTroop(204,"【首都战】购买镜像获得贡献值"),
	CloneTroopItem(205,"【首都战】购买镜像同时获得的道具"),
	CloneTroopItemMaxDay(206,"【首都战】每场购买镜像获得道具的上限数"),
	BerlinDevoteKillNpc(208,"【首都战】杀死敌方NPC得贡献值"),
	TreasureMapGold(210,"【藏宝图】金条宝藏奖励（drop id）"),
	TreasureMapWeight(211,"【藏宝图】各个宝藏的出现权重（转盘权重：色子权重：金条权重：猎人权重）"),
	KFManorMaxRate(217,"【跨服领地战】单人分奖百分比，用的时候除以100"),
	TreasureMapPiece(221,"【藏宝图】藏宝图合成所需碎片id"),
	ArmyDayCostGold(222, "【八一活动】单次（10min）秒cd消耗金砖"),
	ArmyDayCostItem(223, "【八一活动】单次（10min）秒cd消耗道具"),
	ArmyDayReduceTime(224, "【八一活动】秒cd每次减少的cd时间（min）"),
	ArmyDayTimes(225, "【八一活动】每个车搜索次数上限"),
	ArmyDayRefCost(226, "【八一活动】刷新金砖数价格"),
	ArmyDayBossPer(227, "【八一活动】每次鼓舞①攻击增加百分比，用的时候除以100②消耗金砖价格	"),
	ArmyDayBossDropPer(228, "【八一活动】打boss概率掉落"),
	ArmyDayBossPerRew(229, "【八一活动】打boss每掉1/5血掉落"),
	ArmyDayBossLastAtk(230, "【八一活动】打boss最后一击掉落"),
	ArmyDayBossID(231, "boss怪物id，npc_tank表"),
	
	GhostPlayerKill(233,"【国战4】幽灵复仇个人目标"),
	TankResearchAdd(234,"【抽奖】抽奖的SS未获得增加概率"),
	TankResearchSub(235,"【抽奖】抽奖SS获得后概率减少"),
	ArmyDayBossAtk(236, "【八一活动】boss伤害上限，计算系数（公式：系数1 * 玩家总战力^2+系数2 * 玩家总战力 + 系数3"),
	ArmyDayBossTime(237, "【八一活动】打boss冷却时间（s）"),
	ArmyDayBossHp(238, "【八一活动】boss掉落箱子时对应的boss血量值"),
	ArmyDayBossSE(239, "【八一活动】boss活动开启时间"),
	ArmyDayKill(240, "【八一活动】boss击杀--广播"),
	ArmyDayRandom(241, "【八一活动】boss概率宝箱--广播"),
	ArmyDayPoint(242, "【八一活动】boss关键伤害--广播"),
	AgentExpRate(245, "【美女特工】魅力值加成，1点魅力提升多少经验获取速度"),
	AgentIntimacyRate(246, "【美女特工】调教时消耗1点体力亲密度提升1点的概率"),
	AgentExchange(247, "【美女特工】送礼时提升多少点魅力获取1点亲密度"),
	AgentUnlock(248, "【美女特工】技能解锁等级"),
	AgentTrainExp(249, "【美女特工】调教消耗1点体力可得多少经验"),
	AgentCdCount(250, "【美女特工】购买体力一次获得多少体力"),
	AgentRecruitCost(251, "【美女特工】招募特工消耗多少个特工信物"),
	FightEndResetCost(252, "【血战到底】修复单个战车消耗金砖"),
	TankMasterChange(253, "【专精】每天切换时消耗价格（第一次免费）"),
	OverallWarScore(254,"【全面战争】连胜积分递增"),
	RosePrice(255,"玫瑰花单价"),
	FightEndTimes(256, "血战到底，修复次数"),
	BattleCallSoldierResetLimit(257, "【沙场点兵】重置玩法次数上限"),
	AgentComeSingle(263, "【特工来访】活动单抽价格"),
	AgentComeTen(264, "【特工来访】活动十连抽价格"),
	AgentComeLuckyValue(265, "【特工来访】活动幸运满值"),
	Activity101_Circle_Price(269, "【国庆狂欢】在线转盘补转金砖价格"),
	Activity101_Pray_Gold(270, "【国庆狂欢】充值x转，祈福次数+1"),
	Activity101_Pray_Limit(271, "【国庆狂欢】每天祈福次数上限"),
	Activity101_Shop_Limit(272, "【国庆狂欢】充值x金砖，开启特惠商城"),
	Activity101_Shop_Price(273, "【国庆狂欢】每日累计充值x金砖，额外获得1次重置次数"),
	Activity101_Treasure_Rate(274, "【国庆狂欢】聚宝盆计算比例"),
	Activity101_Treasure_V1(275, "【国庆狂欢】玩家日产金砖预估"),
	Activity101_Treasure_First_Down(276, "【国庆狂欢】每天第1次赠送金砖数计算下限"),
	Activity101_Treasure_First_Up(277, "【国庆狂欢】每天第1次赠送金砖数计算上限"),
	Activity101_Treasure_Down(278, "【国庆狂欢】每天第2~x次赠送金砖数计算下限"),
	Activity101_Circle_CD(279, "【国庆狂欢】在线转盘次数获取cd（min）"),
	Activity101_Circle_Limit(280, "【国庆狂欢】在线转盘次数每天上限"),
	Activity101_Circle_Prize(292, "【国庆狂欢】祈福达到x次，额外获得1次祈福次数"),
	Activity101_Treasure_Free(302, "【国庆狂欢】聚宝盆活动首次免费计算比例"),
	MidAutumnTime(281, "【中秋节活动】那兔送福礼包持续时间（分）"),
	WorldBossBuffPrice(282,"【世界boss】购买1次buff花费金砖，伤害增加比例"),
	WorldBossBuffPriceFive(283,"【世界boss】购买5次buff花费金砖，伤害增加比例"),
	WorldBossBuffLimit(284,"【世界boss】购买buff次数上限"),
	CloneTroopLv(286, "【镜像】镜像开放等级"),
	CloneTroopMaxCount(287, "【镜像】镜像世界地图上限"),
	KfExpeditionServerGold(288, "跨服远征固定服务器消耗元宝"),
	KfExpeditionOpenCity(289, "跨服远征解锁城池Id"),
	ExpMoneyRate(290, "【满级】满级后获取经验转成经验币的系数"),
	WorldBossHpRate(291, "【世界boss】复活时间加速比例"),
	ResSuddenStrikeFastPrice(293, "【物资突袭】快速突袭金砖价格"),
	WorldBossHurt(294, "世界boss】boss伤害上限，计算公式： （系数1 +系数2 * 玩家出战战力^2+系数3 * 玩家出战战力）*(1+buff百分比)*浮动系数，浮动系数取0.95~1.15"),
	BlackWarCampTarget(295, "国战5黑鹰阵营目标"),
	MergeRewardTitle(296, "【合服邮件】称号取消补偿"),
	MergeRewardServer(297, "【合服邮件】合服补偿，单份"),
	MidAutumnRandom(299, "【中秋】那兔送福随机事件触发几率"),
	LimitDiscountOpenValue(300, "【限时商店】激活所需金砖数"),
	PresidentPower_ExpRate(301, "【总统特权】【死兵经验系数】"),
	PresidentPower_CenterCity_Time(303, "【总统特权】中心城市持续时间（小时）"),
	PresidentPower_Punish_Time(304, "【总统特权】制裁的持续时间（天）"),
	PresidentPower_Troop(305, "【总统特权】世界部队移动增加秒（秒）"),
	PresidentPower_Policy_Time(306, "【总统特权】军事政策的持续时间（小时）"),
	BlackNpcNum(307, "【国战5】黑鹰叛军数量"),
	Activity13LvLimit(308, "【积分商店】转盘活动开启时，达到xx等级后，同时开启积分商店"),
	MaterialReserveScore(310, "【储备物资】开银箱子排行榜增加积分"),
	MaterialReserveGoldScore(311, "【储备物资】开金箱子排行榜增加积分"),
	WorldBossRecoverySecond(312, "【世界boss】玩家复活时间(s)"),
	WorldBossRecoveryCost(313, "【世界boss】复活消耗锤子数量，锤子不足每个锤子用10金砖抵消"),
	FarWinOpen(315, "【决胜千里】上路（类型2）解锁需要中路（类型1）达到关卡数"),
	FarWinOpen2(316, "【决胜千里】下路（类型3）解锁需要上路（类型2）达到关卡数"),
	
	RaidBattleBoxLimit(322, "【单兵奇袭】各阶段限制箱子数量"),
	RaidBattleHpLimit(323, "【单兵奇袭】限制加血出现次数"),
	RaidBattleTrapLimit(324, "【单兵奇袭】限制陷阱出现次数"),
	ResSuddenStrikeScoreLimit(327, "【物资突袭】单次积分上限阈值"),
	GuildTaskLv(328, "【部落雇佣】部落等级达到x级后功能解锁"),
	Activity11ScrapCost(329, "【双11】刮刮乐每次消耗"),
	CircleBuyChipPrice(330, "【局座转盘】购买歼-20碎片价格"),
	CircleBuyChipGet(332, "【局座转盘】购买歼-20碎片单次获得"),
	
	MagicReformCost(334, "【魔改】单次魔改消耗"),
	MagicRefromAttr(335, "【魔改】魔改初始属性(最终属性=值*等级)"),
	MagicReformSkillLimit(336, "【魔改】一阶魔改普通技能等级上限"),
	MagicReformLimit(337, "【魔改】一阶等级上限"),
	PeakBattleBuyCost(338, "【巅峰挑战】购买次数花费"),
	SuperWeaponUpgradeLimit(339, "【超武扩展】功能开启所需玩家等级"),
	
	WorldBuildReleaseTime(340, "【世界工程】任务发布后持续时间(min)"),
	WorldBuildMineTime(341, "【世界工程】单次部队采集时间(min)"),
	GroupUpFundLv1(343, "【成长基金】成长基金开启等级1"),
	GroupUpFundLv2(344, "【成长基金】成长基金开启等级2"),
	IosUpdateReward(348, "小包热更的奖励"),
	MysteryShopLimit(349, "【神秘商店】每日触发次数上限"),
	MysteryShopMinute(350, "【神秘商店】每日触发后持续时间（min）"),
	MysteryShopSweepScore(352, "【神秘商店】单次兵工厂扫荡，增加幸运值，幸运值到100，触发神秘商店"),
	MysteryShopTaskScore(353, "【神秘商店】单次民情事件完成，增加幸运值，幸运值到100，触发神秘商店"),
	MagicReformTransferCost(354, "【魔改转移】消耗道具"),
	SkipGuideRewards(355, "【新手跳过】一次性奖励"),
	SkipGuideTankExp(356, "【新手跳过】坦克经验7700"),
	
	SoldierCoin(357, "【老玩家回归】单次消费x金砖获得1个老兵勋章"),
	SoldierRmb(358, "【老玩家回归】单次充值xrmb获得1个老兵勋章"),
	SoldierRewrdId(359, "【老玩家回归】老兵勋章道具id"),
	SoldierLost(360, "【老玩家回归】间隔时间，现在是间隔7天"),
	SoldierLast(361, "【老玩家回归】活动持续时间，现在是5天"),
	SoldierPercent(362, "【老玩家回归】7天每天返还离线期间所有资源比例"),
	SoldierKfLost(367, "【老玩家回归】跨服回归，天数"),
	SoldierKfLv(368, "【老玩家回归】跨服回归，等级"),
	
	DiscountFree(369, "【限时折扣（新）】抽折扣免费次数"),
	DiscountLast(370, "【限时折扣（新）】抽折扣后的持续时间（分钟）"),
	DiscountMinVip(371, "【限时折扣（新）】参与活动，最少充值vip点数"),
	DiscountCoin(372, "【限时折扣（新）】每充值多少金砖，获取一个抽奖钥匙"),
	DiscountItem(373, "【限时折扣（新）】折扣券道具"),
	FightCombatSuppress(374, "【战力压制】玩家战力每高100w，自身在战斗中减伤增加5%"),
	ChristSimpleReward(376, "【圣诞活动】普通掉落，每次点击随机一次"),
	ChristBigReward(377, "【圣诞活动】大奖,每整点随机一次"),
	NewYearUnlock(378, "【元旦活动】解锁道具奖池中单个道具所需金砖数"),
	NewYearDis(379, "【元旦活动】老虎机奖励位置禁用1/2/3所需金砖数"),
	NewYearBuy(380, "【元旦活动】老虎机游戏币单次购买价格（金砖）"),
	NewYearMaxTimes(381, "【元旦活动】老虎机游戏币单日购买上限（金砖）"),
	NewYearCost(382, "【元旦活动】老虎机游戏币单次消耗道具"),
	Activity12ScrapCost(383, "【双12】刮刮乐每次消耗"),
	FightCritRate(384, "【战斗公式】暴击概率"),
	FightDogeRate(385, "【战斗公式】闪避概率"),
	DailyTask17Limit(388, "【日常任务】任务精英中，金砖奖励的最小值"),
	Activity19LvLimit(389, "【绘制图纸】服务器中有玩家达到x级，绘制图纸活动开启时，产出翻倍"),
	TankFactoryDelPrice(390, "【绘制图纸】图纸剔除每删除B/A/S/SS（品质1/2/3/4）增加的金砖数"),

	NewYear1Min(391, "【元旦活动】第二个滚轮初始下限"),
	NewYear1Max(392, "【元旦活动】第二个滚轮初始上限"),
	NewYear2Min(393, "【元旦活动】第三个滚轮初始下限"),
	NewYear2Max(394, "【元旦活动】第三个滚轮初始上限"),
	NewYearRandom(395, "【元旦活动】1/2/3/4/5/6/7/8/9数字出现的权重"),
	NewYearTimes(396, "【元旦活动】总倍数≥N，显示广播"),

	RechargeCarnivalUpRankLimit(400, "【跨服充值排行】上榜条件20000砖（2000rmb）"),
	SpringActivity_1(401, "【新年送福】奖池基础金砖数"),
	SpringActivity_2(402, "【新年送福】每充值x金砖奖池增加1金砖"),
	SpringActivity_3(403, "【新年送福】奖池上限值"),
	SpringActivity_4(404, "【新年送福】聚宝盆每日计算比例"),
	SpringActivity_5(405, "【新年送福】玩家日产金砖预估"),
	SpringActivity_6(406, "【新年送福】每天第1次赠送金砖数计算下限"),
	SpringActivity_7(407, "【新年送福】每天第1次赠送金砖数计算上限"),
	SpringActivity_8(408, "【新年送福】每天第2~x次赠送金砖数计算下限"),
	SpringActivity_9(409, "【新年送福】聚宝盆活动首次免费计算比例"),
	SpringActivity_10(410, "【新年送福】集福卡出红包概率"),
	SpringActivity_11(411, "【新年送福】集福卡出红包id"),
	SpringActivity_12(412, "【新年送福】鞭炮每消耗xx金砖获得1个"),
	SpringActivity_13(413, "【新年送福】鞭炮购买1个所需xx金砖"),
	SpringActivity_14(421, "【新年送福】单次鞭炮消耗"),
	SpringActivity_15(426, "【新年送福】红包截止统计时间（年月日时分秒）"),
	SpringActivity_16(427, "【新年送福】红包派奖时间（年月日时分秒）"),
	SpringActivity_17(433, "【新年送福】boss每次驱赶掉血"),
	SpringActivity_18(435, "【新年送福】资源叛军随机掉落"),
	SpringActCost(414, "【过年七天乐】在线转盘补转金砖价格"),
    SpringActTime(415, "【过年七天乐】在线转盘次数获取cd（min）"),
    SpringActMax(416, "【过年七天乐】在线转盘次数每天上限"),
    SpringActIds(417, "【过年七天乐】座驾皮肤id"),
	VipFilterLimit(418,"【封小号】vip等级≥x，不进行过滤"),
	IpLoginLimit(419,"【封小号】同ip下最多能登陆多少个号"),
	IdCodeBindLimit(420,"【封小号】同唯一码最多绑定多少角色"),

	LanternTime(422,"【元宵节活动】那兔送福礼包持续时间（min）"),
	LanternRandom(423,"【元宵节活动】那兔送福随机事件触发几率"),
	SpringActShopTime(432,"【过年七天乐】显示商店购买倒计时（分）"),

	FirstRechargTime(429,"首冲改变tank的时间"),
	FirstRechargTankId(430,"首冲送的坦克ID"),
	FristRechargeGiftIdNew(431,CommValueV2Type.LIST_INT,"首冲礼包(新)"),


	MidAutumnCd(436,"【中秋活动】那兔送福礼包cd时间（min）"),
	LanternCd(437, "【元宵节活动】那兔送福礼包cd时间（min）"),
	
	RoseId77(438,"【7.7情人节活动】玫瑰id"),
	RoseId214(439, "【2.14情人节活动】红玫瑰id"),
	
	FrontBattleRefreshCost(440, "【前线战争】刷新金砖价格"),
	FrontBattleEnemyFree(441, "【前线战争】免费刷新概率"),
	FrontBattleEnemy(442, "【前线战争】金砖刷新概率"),
	
	SpringGameCost(443, "【过年七天乐】接棒子小游戏上限次数，重玩金砖数"),
	Activity79ScrapCost(445, "【限时抢购】刮刮乐每次消耗"),
	AtkMinHurtRate(447, "战斗最小伤害百分比"),
	ActivityThreeDayReward(448, "【三日目标】目标奖励所需分数和奖励"),
	SevenDays(449, "【七日充值】活动完成后大礼包"),
	BattleCallSoldierChoiceGiveUpCost(451, "【沙场点兵】选择弃牌单价"),
	RechargeCarnivalDoubleLimit(452, "【跨服狂欢】双倍奖励门槛"),
	
	FrontBattleEnemyFree2(454, "【前线战争】免费刷新概率"),
	FrontBattleEnemy2(455, "【前线战争】金砖刷新概率"),
	
	Act202UnlockCost(456, "【2月2活动】解锁道具奖池中单个道具所需金砖数"),
	Act202DisableCost(457, "【2月2活动】老虎机奖励位置禁用1/2/3所需金砖数"),
	Act202BuyCost(458, "【2月2活动】老虎机游戏币单次购买价格（金砖）"),
	Act202MaxCost(459, "【2月2活动】老虎机游戏币单日购买上限（金砖）"),
	Act202Cost(460, "【2月2活动】老虎机游戏币单次消耗道具"),
	Act202Random(461, "【2月2活动】1/2/3/4/5/6/7/8/9数字出现的权重"),
	Act202Broadcast(462, "【2月2活动】总倍数≥N，显示广播	"),
	Act202Coins(463, "【2月2活动】每充值x金砖，开高倍们进度+1	"),
	Act202Rate(464, "【2月2活动】开高倍门所需进度"),
	Act202Limit(465, "【2月2活动】低倍下限:上限,下限:上限,高倍下限:上限,下限:上限"),
	Act202OpenTimes(466, "【2月2活动】高倍开启后持续次数"),
	Act202LastTime(467, "【2月2活动】高倍开启后持续时间（min）"),
	QueueBuyCost(468,"【基地城建】解锁第2/3队列所需金砖数"),
	
	BuildInitRes(481,"【基地建设】初始资源"),
	RoseId314(482, "【3.14白色情人节活动】红玫瑰id"),
	ArmyRaceNavyCost(483,"【军备竞赛】海军订单每次升星所需价格"),
	ArmyRaceNLandCost(484,"【军备竞赛】陆军订单每次升星所需价格"),
	ArmyRaceAirCost(485,"【军备竞赛】空军订单每次升星所需价格"),

	TankDriverAd(486, "【军职系统】退伍所需道具"),
	ArmyRacePlayerLv(487,"【军备竞赛】军备竞赛玩家参与等级"),
	ConsumeTowerCost(488,CommValueV2Type.Array_Int,"【消费宝塔】第1-5层每次的消耗金砖数"),


	ConsumeCarnivalUpRankLimit(489, "【跨服消费排行】上榜条件20000砖（价值约2000rmb）"),
	queueSpeedUpFreeTime(490, "【基地】建造时间剩余x秒后加速免费"),
	OneDollarPrice(493, "【1元夺宝】对应的夺宝奖券id"),
	ObstacleCost(495, "【秘境宝藏】清除路障所需价格"),
	DefaultOpenSets(496,CommValueV2Type.LIST_INT,"【设置】默认开启功能索引参数"),
	NavyInitParam(497,"【海军节】潜艇初始耐久，初始弹药数量"),
	NavyHqCost(498,"【海军节】补血花费金砖参数，损失耐久/x"),
	NavyMinRank(499,CommValueV2Type.MAP_INT_INT,"【海军节】上榜条件，总榜，飞机榜，战舰榜，潜艇榜"),
	AnniveraryCakeUpRankLimit(500,"【周年庆】蛋糕上榜条件(个)"),
	NavyHqSpeed(501,"【海军节】海军节航速参数，当前耐久/X"),
	Act51Rate(502,"【五一活动】聚宝盆每日计算比例"),
	Act51FirstRate(503,"【五一活动】聚宝盆活动首次免费计算比例"),
	Act51Pickaxe(504,"【五一活动】十字镐"),
	Act51Detonator(505,"【五一活动】雷管"),
	Act51NTN(506,"【五一活动】炸药包"),
	Act51DayGoldProduct(507,"【五一活动】玩家日产金砖预估"),
	Act51FirstSendDown(508,"【五一活动】每天第1次赠送金砖数计算下限"),
	Act51FirstSendUp(509,"【五一活动】每天第1次赠送金砖数计算上限"),
	Act51TowSendDown(510,"【五一活动】每天第2~x次赠送金砖数计算下限"),
	GuildFactoryUnlockLv(517,"【军工厂】解锁所需部落等级"),
	GuildFactoryProductCost(518,"【军工厂】每个玩家生产1次消耗道具"),
	GuildFactoryScore(519,"【军工厂】每个玩家生产1次增加繁荣度"),
	GuildFactoryStrengthLimt(520,"【军工厂】每天强化次数"),
	GuildFactoryStrengthTime(521,"【军工厂】每次强化时间（min）"),
	GuildFactoryExpOnce(522,"【军工厂】每次增加武器经验"),
	GuildFactoryStrengthCost(523,"【军工厂】每次消耗配件"),
	ArmsOpenCost(524,"【军工厂】解锁武器槽位消耗金砖"),
	BuildRobMaxRate(525,"【基地】征讨单次掠夺资源比例"),
	Act51InitItems(526,"【五一活动】初始道具数量"),
	KfKingCanyonLv(527,"【跨服】王者最小等级"),
	NavyMinCyCleNum(528,"【海军节】保底奖励循环次数"),
	NavyMinSpeed(529,"【海军节】自己潜艇的最低航速每秒"),
	Act51CleanItemId(530,"【五一活动】清除道具id（金币）"),
	RepairTrainCost(534,"【维修训练】消耗"),
	RepairTrainFirstReward(538,"【维修训练】每日首次奖励"),
	RepairTrainScoreLimit(541,"【维修训练】单次玩法积分上限（后端防作弊用）"),
	
	FightEndIds(543,"【血战到底】扫荡关卡数"),
	
	ReareTreasureCostRate(544,"【秘境宝藏】简单、困难、噩梦耗油比例"),
	BuildAutoSecond(546,"【基地】自动建造时间（s）"),
	TankResearchFreeItem(547,"【高级研究】高研消耗单抽券"),
	TankOilDiscount(549,"【跨服】跨服石油打折"),
	RoseId520(553, "【5.20情人节活动】红玫瑰id"),
	FightSkillDodgeParm(556, "【伤害计算】技能闪避率计算系数，技能闪避率 = 物理闪避率*参数1+参数2，最小值：参数3，最大值：参数4"),
	KingTitleDel(559, "【合服邮件】最强王者称号取消补偿"),
	
	TroopAdvanceSkill(560, "突进技能生效时间"),
	TankJingzhuCommonCost(563, "坦克精随机铸普通消耗"),
	TankJingzhuCost(564,CommValueV2Type.LIST_ITEM2, "坦克精随机铸高级消耗"),
	TankJingzhuCommonWeight(565, "坦克精随机普通，权重"),
	TroopAdvanceWeight(566, "坦克精随机高级，权重"),
	CaptiveTankTime(567,"【俘虏营】俘虏时间"),
    CaptiveRedeemCost(568,"【俘虏营】赎回每分钟价格（金砖）"),
	TankSecondWill(569,"【奇兵】每秒恢复战意值"),
    TankLoseHpWill(570,"【奇兵】坦克每掉1%耐久恢复战意值"),
    CityScoreRatio(571,"【阵营积分】城市产出增加阵营积分 = 参数1*本阵营积分/最大阵营积分"),
    CityFightScore(572,"【阵营积分】积分战排名0/1/2/3增加阵营积分"),
    CityStageScore(573,"【阵营积分】城池战(攻城争霸战)完成目标1/2/3对应增加阵营积分"),
    GhostRevengeScore(574,"【阵营积分】幽灵战完成阵营增加积分"),
    BerlinWarWinScore(575,"【阵营积分】首都战获胜阵营增加积分"),

    CampAngerRatio(576,"【阵营积分】判断是否参加国战的积分临界值；≤临界值时的增加的基础积分参数；>临界值时的增加的基础积分参数;触发弱阵营任务所需怒气值"),
	CampConvertRatio(577, "转阵营金砖计算"),
    CampAngerLimit(578,"【阵营悬赏】悬赏开启的怒气值上限"),
    EnemyToWallSCore(579,"【阵营积分】国战5黑鹰军完成目标增加阵营积分"),
    
	Activity0801_Pray_Gold(580, "【八一活动】充值x转，祈福次数+1"),
	Activity0801_Pray_Limit(581, "【八一活动】每天祈福次数上限"),
	Activity0801_Shop_Limit(582, "【八一活动】充值x金砖，开启特惠商城"),
	Activity0801_Shop_Price(583, "【八一活动】每日累计充值x金砖，额外获得1次重置次数"),
	Activity0801_Treasure_Rate(584, "【八一活动】聚宝盆计算比例"),
	Activity0801_Treasure_V1(585, "【八一活动】玩家日产金砖预估"),
	Activity0801_Treasure_First_Down(586, "【八一活动】每天第1次赠送金砖数计算下限"),
	Activity0801_Treasure_First_Up(587, "【八一活动】每天第1次赠送金砖数计算上限"),
	Activity0801_Treasure_Down(588, "【八一活动】每天第2~x次赠送金砖数计算下限"),
	Activity0801_Circle_Prize(589, "【八一活动】祈福达到x次，额外获得1次祈福次数"),
	Activity0801_Treasure_Free(590, "【八一活动】聚宝盆活动首次免费计算比例"),
	BerlinBossHp(591,"柏林战boss血量"),
    BerlinBossDayMaxCount(592,"柏林战boss玩家每日最大攻打次数"),
	CaptiveTroopMax(593,"【俘虏营】一支队伍最多被俘虏坦克"),
	CaptivePlayerMax(594,"【俘虏营】每人最多同时被俘虏次数"),
	SuperMagicReformCost(595,"【魔改】sss消耗道具"),
	BerlinBossFucVal(596,"柏林战boss战斗公式"),
	BuildHunterHour(598,"【领地】水晶猎人生成时间点"),
	Act97RankMin(600, "【6周年活动-充值排行】排行榜上榜条件5000砖（价值约500rmb）"),
	Act97CritRate(601, "【6周年活动-充值转盘】转盘第5次必暴击"),
	Act97Quality(602, "【6周年活动-充值转盘】品质≥x，显示记录"),
	Act97Circle(603, "【6周年活动-充值转盘】每充值每300vip点获得道具"),
	MergerServerGold(604, "【合服-消费排行】上榜所需消砖数"),
	DoubleNinthActivity_4(607, "【重阳节】聚宝盆每日计算比例"),
	DoubleNinthActivity_5(608, "【重阳节】玩家日产金砖预估"),
	DoubleNinthActivity_6(609, "【重阳节】每天第1次赠送金砖数计算下限"),
	DoubleNinthActivity_7(610, "【重阳节】每天第1次赠送金砖数计算上限"),
	DoubleNinthActivity_8(611, "【重阳节】每天第2~x次赠送金砖数计算下限"),
	DoubleNinthActivity_9(612, "【重阳节】聚宝盆活动首次免费计算比例"),
	DoubleNinthActivity_10(613, "【重阳节】集福卡出红包概率"),
	DoubleNinthActivity_11(614, "【重阳节】集福卡出红包id"),
	DoubleNinthActivity_12(615, "【重阳节】鞭炮每消耗xx金砖获得1个"),
	DoubleNinthActivity_13(616, "【重阳节】鞭炮购买1个所需xx金砖"),
	DoubleNinthActivity_14(617, "【重阳节】单次鞭炮消耗"),
	DoubleNinthActivity_17(618, "【重阳节】boss每次驱赶掉血"),


	LimitedTimeSecondsKillTimePoint(619, "【双11-限时秒杀】每轮开始时间点"),
	LimitedTimeSecondsKillTimes(620, "【双11-限时秒杀】每轮持续时间（min）"),
	LimitedTimeSecondsKillMachineId(621, "【双11-限时秒杀】扣除剩余商品的物理机ID"),
	consume_gold_get_integral(623, "【双11-狂欢盛典】每消耗x金砖获得1点积分"),
	double_11_lucky_value(624, "【双11-狂欢盛典】每次转盘增加幸运值"),
	double_11_lucky_value_max(625, "【双11-狂欢盛典】幸运值上限"),
	double_11_integral_user_one(626, "【双11-狂欢盛典】血拼积分一次抽奖积分消耗"),
	double_11_integral_user_ten(627, "【双11-狂欢盛典】血拼积分十次抽奖积分消耗"),
	double_11_item_ids_clear(628, "【双11-狂欢盛典】活动结束后需要清空的道具ID"),
	BattleCallSoldierSoulNum(629,"【沙场点兵】关卡对应奖励数量"),

	KFScuffle_Res_Init(631,"【跨服极地乱斗】初始单人核晶"),
	KFScuffle_MinLv(635,"【跨服极地乱斗】参加等级"),
	FIRST_RECHARGE_GIFT_TWO(636,"【首冲礼包2】累充480金砖奖励"),
	FIRST_RECHARGE_GIFT_THREE(637,"【首冲礼包3】累充1280金砖奖励"),
	AircraftDrawLuckInit(651,"【航母战机十连抽】红色战机初始概率"),
	AircraftDrawLuckAdd(652,"【航母战机十连抽】抽奖未获得红色战机增加概率"),
	AircraftDrawLuckReduce(653,"【航母战机十连抽】抽奖获得红色战机后概率减少"),
	KFSeasonPlayerScoreReward(648,"【跨服赛季】个人战功≥15000后可领取奖励"),
	KFSeasonRate(650,"【跨服赛季】xx名之前（包括xx名）的服务器开启冠绝商店，xx = 向上取整（参数1 * 排行榜服务器数量  / 5）* 5"),
	CarrierStrike_map_relation(654, "【航母出击】地图关联关系"),
	CarrierStrike_item_ids_clear(655, "【航母出击】活动结束后需要清空的道具ID"),
	LevelEventSupporCost(656,"【等级事件（新）】购买支援消耗钞票"),
	BattleAchievementId(657, "【航母出击】战功道具 ID"),
	ControlPosColorInit(658, "【中控】初始1-9位置对应颜色"),
	ControlPosColorDismantle(659, "【中控】拆除1个元件所需道具"),
	ControlPosColorTransf(660, "【中控】转移所需道具"),
	ControlPosColorResearch(661, "【中控】研究室消耗研发材料"),
	ColorWeight(664, "【大军压境】1-层库，4-6层库"),
	MonthGiftLimitLevel(662, "周月礼包 开启等级限制"),
    ArmyPressBorderFightCount(665, "【大军压境】每轮的奇袭次数"),
    ArmyPressBorderInit(666, "【大军压境】每轮生成的层数"),
    ArmyPressBorderCostRare(667, "【大军压境】耗油系数"),
	ArmyPressBorderRare(668, "【大军压境】判断一格内相同颜色时，该颜色的权重倍数除以10"),
	ArmyPressBorderScoreRare(669,CommValueV2Type.Array_Double, "【大军压境】消除3,4,5及以上个数时的系数"),
	ArmyPressBorderConMax(670, "【大军压境】同时消除多个军工倍数上限"),
	ArmyPressBorderNpcLv(671, "【大军压境】同时消除多个军工倍数上限"),
	ArmyPressBorderScore(672, "【大军压境】同时消除多个军工倍数上限"),
    BUY_EVERY_DAY_POINTS(3001,CommValueV2Type.MAP_INT_INT, "【每日必买】第1/2/3个箱子增加积分值"),
	BackFlowReward(713, "老用户回流奖励"),
	MidAutumn2021_1(714, "【新中秋活动】锦鲤抢红包开启和结束时间"),
	MidAutumn2021_2(715, "【新中秋活动】锦鲤红包开奖时间"),
	MidAutumn2021_3(716, "【新中秋活动】锦鲤红包每日大奖,随机将三个大奖分配给中奖的三个玩家且大奖都是唯一的"),

	TankEvoGiftMax(718, "【超进化礼包】玩家最多可触发战车超进化总次数，比如填写5，表示单个玩家最多只能触发五辆不同SS战车的超进化礼包商城"),
	TankEvoGiftTime(719, "【超进化礼包】单个战车礼包持续时间（小时）"),

	Act113Rank1(720, "【情人节113】亲密度榜上榜条件"),
	Act113Rank2(721, "【情人节113】充值榜上榜条件"),
	Act113Rank3(722, "【情人节113】消费榜上榜条件"),
	SmallGameCostEn(723, "【小游戏】每次挑战消耗体力"),
    FriendLimit(728, "好友数量上限"),
    KFChatGold(729, "跨服聊天消耗"),
    RichManValueTimes(730, "【清明节ID：20】资源运输车单次持续时间（秒）"),
    RichManValueLimit(731, "【清明节ID：20】资源运输车每日重置次数上限"),
    RichManValueLocation(732, "【清明节ID：20】资源运输车出现位置"),
	RichManValueRate(733, "【清明节ID：20】资源运输车后期刷新几率"),
    RichManDiceRankLimit(734, "【清明节ID：20】投掷次数上榜条件"),
    RichManCostRankLimit(735, "【清明节ID：20】消费上榜条件"),
    EvolveStarServerLv(736, "【超进化商城】开启所需最小服务器等级"),
    EvolveStarDefaultTankId(738, "【超进化商城】玩家没有SS车时，默认可选的战车"),
	EvolveStarNum(739, "【超进化商城】当前服务器第N个玩家有SS战车进化到红5星"),
    EvolveStarCanOpenTime(742, "【超进化商城】更新后生效时间，在2022年4月14日更新之后再经过3天再生效，避免部分玩家已触发旧超进化商城"),
    TankResearchJuniorMaxTime(743, "【坦克研究】坦克研究最大研究次数，一次抽5个"),
    AgentCenterLimit(744, "【特工中心】解锁条件：当玩家解锁X个特工之后"),

    ActivitySevenDayReward(745, "【七日目标】目标奖励所需分数和奖励"),

    RareTreasureSweepCost(746, "【秘境宝藏】简单、困难、噩梦扫荡耗油固定数值"),
    Act81_Bullet_Num(748, "【建军节】弹幕重复滚动数量上限"),
	Act117Reward(749, "【14日活动】奖励配置道具ID：数量，道具ID：数量，"),
	Act117RewardCost(750, "【14日活动】补签1次消耗金砖数量"),
	Act117Gift(751, "【14日活动】灰熊升星礼包ID：礼包数量：持续时间（小时）"),
	Act117NeedTaskPoint(752, "【14日活动】补签1次需要的日常活跃点数最小值"),
	Recharge120UpRankLimit(756, "【跨服充值排行】上榜条件10000砖（1000rmb）"),

	Act119DrawCost(757, "【座驾降临】单次抽奖消耗道具和数量，多次是多个对应数量，比如点击连抽5次，消耗5个"),
	Act119CloseDelete(761, "【【座驾降临】活动结束需要清除的道具"),

    CampTickeRankLimit(764,"【阵营弹劾】弹劾同意与否资格，必须满足战力达到本阵营前X名"),

    SuperMagicReformSkillLimit(771, "【魔改】超级魔改普通技能等级上限"),
    SuperMagicReformLimit(772, "【魔改】【魔改】二阶魔改等级上限"),
	SuperMagicReformOpenLv(773, "【魔改】【魔改】二阶魔改要求坦克等级"),
    MagicReformCost2(774,"【魔改】ss二阶消耗道具"),
    SuperMagicReformCost2(775,"【魔改】sss二阶消耗道具"),
	TransportThrowLimit(779,"【清明节ID：20】资源运输车可投掷次数上限" ),

	Act119ItemId(780, "【座驾降临】军需物资碎片在2期和3期依然可以继续使用（道具ID：60506，军需物资碎片）"),
	Act117LastReward(781, "【14日活动】灰熊升星礼包ID，12月6日补偿,12月7日登陆邮件自动发送"),
	PRESIDENT_HEAD_ICON(788, "添加首都战 大总统头像"),
	Zero_Init_DateStr(791, "0元礼包生效限制"),
	Strength_LvCost_Limit(794, "【力量系统】强化时一键添加最多X个力量零件作为当前零件升级所需消耗"),
	AgentDispatch_1(796, "【特工派遣】可派遣特工最大数量"),
	AgentDispatch_2(797, "【特工派遣】恢复1点体力用时（秒）"),
	AgentDispatch_3(798, "【特工派遣】一点体力可以派遣多久（秒）"),
	AgentDispatch_4(799, "【特工派遣】至少拥有多少体力才可以被派遣"),
	AgentDispatch_5(800, "【特工派遣】派遣体力上限，达到上限不再恢复"),
	AgentDispatch_6(801, "【特工派遣】固定产出内容"),
    ShareDeskReward(3002, "【快捷桌面】生成快捷桌面后可领取的奖励"),
	MagicReformResetCost(806, "【魔改重置】消耗道具"),
	FishContinuousPerfect(807, "【钓鱼】最高可连击的次数"),
	FishDoubleScore(808, "【钓鱼】连击后的双倍生效的次数"),

    TankLotteryVipNum(4003, "【空中拦截】每个vip等级增加的购买数量"),
    TankLottery18Num(4004, "【空中拦截】18点之前可以购买的数量"),
    TankLotteryBigRewardNum(4005, "【空中拦截】根据总购买数量推算总的大奖数量"),
    TankLotteryBigRewardGiftId(4006, "【空中拦截】大奖id"),
    TankLotteryBaseRewardGiftId(4007, "【空中拦截】保底奖励"),
    TankLotteryTotalNum(4008, "【空中拦截】21点之前可以购买的数量"),

	SeasonVipCard_Buf1(4011, "【至尊季卡】激活后自动挂机石油上限200w"),
	SeasonVipCard_Buf2(4012, "【至尊季卡】激活后航运币上限提高到N倍"),
	SeasonVipCard_Buf3(4013, "【至尊季卡】镜像价格折扣"),
	Strength_Lucky_Limit(4014, "【力量零件抽奖】幸运值上限"),
	Strength_Single_Cost(4015,CommValueV2Type.LIST_ITEM, "【力量零件抽奖】单抽消耗"),
	Strength_Ten_Cost(4016, CommValueV2Type.LIST_ITEM,"【力量零件抽奖】十连消耗"),
	Strength_Single_Gold_Cost(4017, "【力量零件抽奖】力量研发许可金砖单价"),
	Strength_Buy(4018, "【力量零件抽奖】力量研发许可每日可用金砖购买最大上限"),
	SeasonVipCard_Buf4(4019, "【至尊季卡】特工体力上限提升到X"),

	Act2055LvLimit(5004, "【新服赢财神】多少级展示入口"),
	Act2055Day(5005, "【新服赢财神】触发后多少天后关闭（自然天）"),
	OneAnswerTime(5006, "【答题】每题倒计时（秒）"),
	ANSWER_NUM(5007, "【答题】总题数"),
	Act19Times(5008, "【绘制图纸】每天幸运降临刷新次数"),
	Act19SSTankId(5009, "【绘制图纸】每天幸运降临刷新次数"),
	FriendGiftDrop(5010, "好友送礼"),
	CampAlliance(5011, "同盟提前解除，不判断时间点"),
	GZYXQ(5012, "【关注游戏圈】关注游戏圈后可领取的奖励"),
	Act125Limit(5015, "【连续充值】充值达到多少vip点触发开启"),
	TradeGDUnLock(5013, "【贸易股东】解锁公司等级"),
	TradeGDShareRate(5014, "【贸易股东】大股东分走比例"),
	MainMissionBuff(5017, "【主线】动态难度"),
	TradeGDRandom(5018, "【贸易-公司股东】流失子公司作弊上缴航运币"),
	TradeGDLeaveRate(5019, "【贸易-公司股东】流失子公司每日*概率上缴作弊航运币"),
	TradeGDMaxCount(5020, "【贸易-公司股东】流失子公司每日*概率上缴作弊航运币上缴次数"),

	ShareDayMax(5022, "今日最多分享次数"),
	ShareDayCD(5023, "分享CD"),
	ShareReward(5024, "分享奖励id"),
	TreasuryMaxInterval(5025, "【新征收】最大累计时间（分钟）"),
	TreasuryMinInterval(5026, "【新征收】最小征收间隔（分钟）"),
	TreasuryCostInterval(5027, "【新征收】快速征收 时间（分钟）"),
	ConvertCampPrice(5028, "【转阵营】最强阵营价格"),

	FIRST_RECHARGE_GIFT_Card(5029,"【首冲礼包3】自尊月卡体验"),
	HF_Server_RebelItem(5030,"【资源叛军】合服后叛军奖励"),

	SubVipTreasuryMax(5031,"【订阅vip】新征收最大累计时间"),
	SubVipShooting(5032,"【订阅vip】打靶跳过"),
	GuildFactoryProduceLimit(5033,"【军工厂】每人每天提交材料的上限"),
	Act2058Limit(5034, "【转端充值返利】单笔金额触发返利的vip点"),
	Act2058Rate(5035, "【转端充值返利】返还比例 需要除以100"),
	DYSideBar(5036, "抖音侧边栏"),
	MissionBoxMaxMinute(5038, "【挂机奖励】最大时间（分），超出不获得"),
	TroopUnlockMissionIds(5041, CommValueV2Type.Array_Int,"【编队】编队解锁条件"),

	TankSkillUnlockLvs(5037, CommValueV2Type.Array_Int,"【坦克技能解锁】对应坦克等级"),
	TankLvUpCostItemId(5040, "【战兽升级】消耗道具"),
	TroopUnlockMissions(5041, "【编队】编队解锁条件（第一队解锁条件关卡顺序ID,第二队解锁条件关卡顺序ID，...）"),
	TankResetCost(5042, "【战车重置】重置道具"),
	GuildFlag(5043,"【部落】旗帜元素上限：旗帜背景数量，旗帜背景颜色色数量，旗帜主图案数量，旗帜主图案颜色数量"),
	GuildActiveDay(5044,"【部落】活跃最大天数"),
	GuildActiveTotal(5045,"【部落】部落活跃数量范围"),
	GuildOnceNum(5046,"【部落】部落每次取的数量"),
	GuildApplyTime(5047,"【部落】部落申请存在时间（小时）"),
	TankResearchItemIds(5049, CommValueV2Type.MAP_INT_INT,"【驯化】品质对应的道具"),
	LuckyWishRate(5051,"【十连抽】随机到ss车时，出心愿单权重概率"),
	LuckyMustSTankTimes(5052,"【十连抽】第xx次必中s品质及以上战车"),
	LuckyItemCost(5053,"【十连抽】十连抽道具价格"),

	BeastFightDayNum(5059,"【兽王试炼】每日战斗次数"),
	BeastFightMaxFrame(5060,"【兽王试炼】战斗最大帧数"),

	TowerBuffPosUnlockMission(5064, CommValueV2Type.Array_Int,"【驭魂之地】4个buff槽位的解锁条件（=已通关最大关卡，0为默认解锁）"),
	ChangeGuildFlagCost(5066,"军团旗帜修改价格（金砖）"),
	TroopRecoverHp(5069,"部队回血"),
	CloneTroopCost(5070,"部队clone消耗（金砖）"),

	TankResearchFreeTimes(5072,"【十连抽】每日免费次数"),
	TankResearchFreeTimesCd(5073,"【十连抽】免费次数的冷却时间(秒)"),
	OffLineBoxMaxTime(5074,"【离线奖励】最大时间（分），超出不获得"),
	OffLineBoxStartTime(5075,"【离线奖励】离线最大时间（分），超出此时间开始累积"),


	GuildWarTime(5100, "部落战开启时间"),

	;


	/**
	 * @param type
	 * @param desc
	 */
	private CommonValueType(int type, String desc) {
		this.type = type;
		this.desc = desc;
		this.v2Type = CommValueV2Type.None;
	}
	private CommonValueType(int type, CommValueV2Type v2Type,String desc) {
		this.type = type;
		this.desc = desc;
		this.v2Type = v2Type;
	}

	private int type;
	private String desc;
	private CommValueV2Type v2Type;

	
	public static CommonValueType getCommonType(int type) {
		for (CommonValueType commonType : CommonValueType.values()) {
			if(commonType.getType() == type) {
				return commonType;
			}
		}
		return null;
	}
	
}
  
